---

version: '3.8'

services:
  app:
    working_dir: /var/local/app/
    build: .
    volumes:
      - bundle-install:/usr/local/bundle
      - ${PWD}/app/:/var/local/app/
    ports:
      - 3000:3000

volumes:
  bundle-install:
    driver: local
